name: Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Create Branch
        run: |
          # Issue 번호 추출
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          # branchName 필드 추출 (Issue Form 형식에 맞춤)
          BRANCH_NAME="feature/${ISSUE_NUMBER}-$(echo '${{ github.event.issue.body }}' | grep -A1 'branchName' | tail -n 1 | tr -d '[:space:]')"

          # git 설정 및 브랜치 생성
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
