# .github/workflows/create-branch-from-issue.yml
name: Create Branch from Issue

on:
  # for .github
  issues:
    types: [opened]
  # for other repository
  workflow_call:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Create Branch
        run: |
          # Issue 번호 추출
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          # branchName 필드 추출
          BRANCH_NAME_PART=$(echo '${{ github.event.issue.body }}' | sed -n '/^### 브랜치 이름/,/^###/p' | sed '1d;$d' | tr -d '\n' | tr -d ' ')

          # 최종 브랜치 이름 생성
          BRANCH_NAME="feature/${ISSUE_NUMBER}-${BRANCH_NAME_PART}"

          # git 설정 및 브랜치 생성
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
